# production environment
# based on `docker-compose.yml`

version: '3.2'

services:
  db:
    restart: always
  app:
    restart: always
    ports:
      - 81:80
  phpmyadmin:
    restart: always
    ports:
      - 82:80