version: '3.2'

services:
  db:
    image: mariadb:10.2
    volumes:
      - ./volumes/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # database created on image startup
      MYSQL_DATABASE: lo1olkusz
  app:
    image: pjanczyk/lo1olkusz-backend-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: lo1olkusz
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    environment:
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
